
export let StaticIndexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Static Site</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <h1>Welcome to My Static Site</h1>
  <p>This is a sample static site generated by JungleWriter.</p>
</body>
</html>
`;

export let StaticStylesCss = `
`
